### ISSUE TITLE
Restore delta files in Data Downloads section

### ISSUE THREAD

**Issue by kaitlin** [fedspendingtransparency/USASpending-Issue-Tracker#17]
Previously on USASpending.gov, the Data Downloads section had the delta files that included transactions that had been added since the last reporting period. These should be restored.

**Comment by rmaziarz** [comment]
This feature has been restored here: https://www.usaspending.gov/DownloadCenter/Pages/dataarchives.aspx

If users have additional issues with this feature, please report them.
