### ISSUE TITLE
SSL Cert error

### ISSUE THREAD

**Issue by KatherineMichel** [fedspendingtransparency/USASpending-Issue-Tracker#18]
I went to the website and got a Security Certificate error. Sometimes this happens when a SSL Cert was diy. I've never had this happen with a Government-associated website before. Frankly, it looks shady.

**Comment by kaitlin** [comment]
thanks for reporting @KatherineMichel ! It looks like the certificate needs to be reissued for the bare usaspending.gov domain, but it does work for www.usaspending.gov. For now, you should be able to access the page with the www prefix without receiving the warning: https://www.usaspending.gov/. We'll look into this further.
