### ISSUE TITLE
Top Prime Recipients Section of State Summaries

### ISSUE THREAD

**Issue by jgaviglio** [fedspendingtransparency/USASpending-Issue-Tracker#20]
This section repeats recipients (Two Raytheons) with different amounts and the text case is mixed, some all upper, some proper:
https://www.usaspending.gov/transparency/Pages/StateSummary.aspx?StateCode=MA&fiscalyear=2015

![image](https://cloud.githubusercontent.com/assets/11860425/7095630/db2ea92e-df99-11e4-978d-262a015f23f0.png)

**Comment by USAspendingalice** [comment]
This issue has been resolved.

**Comment by jgaviglio** [comment]
Hi Alice,

I can’t see what got changed for this issue?

Thanks!
John

**Comment by USAspendingalice** [comment]
You may continue to see a company listed in the Top Prime Recipients more than once because the data is displayed by the DUNS reported for the award(s) and many companies have more than one DUNS.  For example, Raytheon Company has approximately 136 DUNS numbers -- the amount(s) of the award(s) reported to that DUNS could put the company in the Top 10 more than once.

**Comment by jgaviglio** [comment]
We used the Mod_Parent field instead when we downloaded data from the data archives. Do you recommend that over the DUNS? It still had multiples of the same contractor but not as many.

John

**Comment by USAspendingalice** [comment]
Thank you for your question. Can you clarify what question you're trying to answer so we can provide a clear response?

**Comment by jgaviglio** [comment]
Hi Alice,

Is the DUNS numbers the best data field to aggregate on for vendor dollars obligated summaries? I used the Mod_parent field.

Thanks,
John
[cid:image001.gif@01D0E0AD.FCAD3C40]

John Gaviglio
State Data Center Manager
Economic and Public Policy Research
---
UMass Donahue Institute
100 Venture Way, Suite 9
Hadley, MA 01035
Office: (413) 545-0176
Web: http://www.donahue.umassp.edu<http://www.donahue.umassp.edu/>

**Comment by USAspendingalice** [comment]
Yes, the DUNS number field is the best field to use to identify specific vendor data. The mod_parent field is a text field so it might not be unique to a specific vendor. 
Also, if you want to contact us directly you can email usaspending@fiscal.treasury.gov.
