### ISSUE TITLE
USAspending.gov stripping/dropping characters and/or Zeros

### ISSUE THREAD

**Issue by michaelmcclellan** [fedspendingtransparency/USASpending-Issue-Tracker#21]
Noticed in the data download extract seems to be stripping leading zeros from several fields  listed below. This is a huge concern since when we pull the file up in CSV, its making the codes list below wrong for several area by dropping the leading zero’s or leading characters. These fields are key to our ability of having accurate data and reflecting the data that was accurately submitted to USAspending.gov.  Is there a projected date as to when this will be rectified? We sent this to Treasury on 4/2 with a reply back that it is being sent to the development team for review. To date we have not heard of any resolution to this issue.
  
Below are the data fields that are being stripped of characters and leading zero. 
  
1.)    Recipient City Code – Column header: H 
2.)    Recipient County Code – Column header: J 
3.)    Recipient Zip Code – Column header: L 
4.)    Principle Place Performance Code – Column header: AB 
5.)    Principle Place Zip Code – Column AE 
6.)    Principle Place of Performance Congressional District: AF 
7.)    DUNS number – Column: AX

**Comment by kaitlin** [comment]
Thanks for reporting @michaelmcclellan! I will check in with the team on the status and post an update as soon as I have one.

**Comment by USAspendingalice** [comment]
@michaelmcclellan We are closing this issue.  When the extract is opened in a text editor, the leading zeros are displayed.  It is likely that the zeros are being stripped in your spreadsheet application.  Thank you for your feedback and your patience as we continue to make improvements in the site.

**Comment by michaelmcclellan** [comment]
I’ve attached the original document and email sent on 4/2/2015 for the record.

This data pull came from USAspending.gov data download and not from any spreadsheet generated on our end.

In the original correspondence with GitHub it mentioned it was confirmed and in progress…..so the question still stands unless the issue has been rectified.

Kind regards,

Michael O. McClellan
Program Analyst
Division of Financial Assistance Policy & Oversight (FAPO)
Office of the Chief Financial Officer (OCFO)
U.S. Department of Homeland Security (DHS)
Office: 202.447.5161
Mobile: 202.407.3513
Michael.Mcclellan@hq.dhs.gov

[cid:image001.gif@01CB9C38.C5817B50]

**Comment by bsweger** [comment]
Hi @michaelmcclellan: thanks for circling back on this.

I checked this again and can confirm that the leading zeros are in the .csv file produced by USAspending. If you're using a spreadsheet program like Excel to open the downloaded .csv, it's that program which is stripping the leading zeroes. 

Here's an example of what I see when opening the .csv in a text editor. The zip code (circled below) has its leading zero:

![usaspending zip code](https://cloud.githubusercontent.com/assets/540544/7937842/306817fa-0910-11e5-89bf-aba6f13a5b2f.png)

One workaround is to open Excel first and then import the .csv as a separate step ([directions here](https://support.office.com/en-in/article/Import-or-export-text-txt-or-csv-files-e8ab9ff3-be8d-43f1-9d52-b5e8a008ba5c#bmimport_data_from_a_text_file_by_openi)). This allows you to specify which columns should be treated as text and, thus, keep their leading zeroes. Once you do the import with leading zeroes intact, you can save the file as .xls, and it will keep the zeroes. 

I've also added an idea for a future enhancement (#68) to explore adding Excel-friendly .csv files. This is a personal idea, nothing official. It will have to be evaluated by the project team in the same way they evaluate other such requests.

**Comment by michaelmcclellan** [comment]
Thanks Becky it is greatly appreciated.

This  would be nice if they can add this as a future enhancement #68 and not have this generate the report in  such a fashion that it creates confusion.

Kind regards,

Michael O. McClellan
Program Analyst
Division of Financial Assistance Policy & Oversight (FAPO)
Office of the Chief Financial Officer (OCFO)
U.S. Department of Homeland Security (DHS)
Office: 202.447.5161
Mobile: 202.407.3513
Michael.Mcclellan@hq.dhs.gov

[cid:image001.gif@01CB9C38.C5817B50]
