### ISSUE TITLE
Advanced Data Search Features with Spending Types and extract files

### ISSUE THREAD

**Issue by michaelmcclellan** [fedspendingtransparency/USASpending-Issue-Tracker#23]
There are several issues in the advance data search as follows:
1.)	Advance Data Search Feature – When selecting multiple “Spending Types” it limits the number of Fiscal Years one can select. Thereby, creating a burdensome for users with having to run multiple reports when needing to review multiple years (more than 3). The old USAspending.gov feature allowed for the user to select multiple years. The current state is not user friendly and is a workload burden on users. Please bring back or enable/enhancement to this feature to allow multiple FY searches regardless of how many spending types a user selects.
2.)	Also for “Spending Types” there used to be a category for Direct Payments and Insurance (now all under “Other Financial Transactions.” There does not seem to be a category for direct pay or insurance. These spending types feature should be brought back for a more simplified report for those types. Thereby, allowing a more detailed report and not have to pull “other Financial Assistance” and get data one doesn’t need.  The current features are limiting and not user friendly and find the Advance Search Feature more of a burdensome issue when trying to run or retrieve data. Please bring back all those additional spending types, please. 

3.)	Advanced Data Search Extract File - with the extract file not sure what the intent of this extract file is? It’s limited in the FFATA format and what data fields are there (currently 12 data elements only) are difficult to filter rendering the files useless.
Should the extract at least have the minimum FFATA data elements?

**Comment by bsweger** [comment]
@michaelmcclellan Thanks for taking the time to leave this feedback. I'm going to separate your three items into separate issues to make sure we capture everything you wrote. In the meantime, I'll leave this issue open as a placeholder.

**Comment by bsweger** [comment]
@michaelmcclellan I've opened two new issues to reflect your first two suggestions about the Advanced Data Search screen:

* #36 (remove limit on fiscal year selection)
* #37 (add direct payment and insurance spending types)

I think your third request is reflected in #13, which asks that data downloads from the advanced search screen include the awards' full records (and it looks like you've weighed in on that discussion).

I'm going to close out this one. Thanks again for the feedback!
