### ISSUE TITLE
DOD FY14 Spending map is wrong

### ISSUE THREAD

**Issue by mcpeate** [fedspendingtransparency/USASpending-Issue-Tracker#26]
FY14 DOD spending map for contracts is wrong. DOD's FY14 contract-spend total on the right-hand side of the page totals $69B when the correct amount is closer to $284B.
Screenshot attached: 
![fy14-dod-contracts-error](https://cloud.githubusercontent.com/assets/4594518/7073998/54ce11be-dec5-11e4-9d6f-db2982dc6dbc.jpg)

**Comment by kaitlin** [comment]
Thanks for reporting @mcpeate! I think this might be the same underlying issue as #22, but I will leave this open for now as we look into both.

**Comment by mcpeate** [comment]
Agreed @kaitlin re: similar issue to #22. I just wanted to confirm that this problem was global rather than local. If I had to guess, I suspect the pull is failing to include Army, Navy, and AF contract spend in DOD's spending totals.

**Comment by bsweger** [comment]
@mcpeate USASpending has been updated with a fix to address this issue. I now see $290.75 billion for DOD FY 2014 contracts. Does the DoD map search now work as you would expect?

**Comment by mcpeate** [comment]
@bsweger Yes, it works for me as well. Thanks. (Though the spending map contract dollars/actions does not exactly match DOD's reported 2014 agency profile contract dollars/actions)

**Comment by bsweger** [comment]
Thanks, @mcpeate. I checked in with the team about the different amounts on the map view vs the agency profile page. The map view amounts reflect awards data with a US-based place of performance (geocoded by zip), whereas the agency profile page reflects all awards reported by the agency.

I'll add this info to #22 so the clarification is noted in both places.

**Comment by bsweger** [comment]
Should have added: if you're satisfied that this issue is fixed, I'll go ahead and close. Thanks again for reporting.

**Comment by mcpeate** [comment]
@bsweger The more I think about this, the more confused I get. Is the $285B on the spending map detailing prime recipients whose place of performance is the US? If so, the coding is incorrect as the not all contract spend is awarded to prime recipients in the US.

**Comment by mcpeate** [comment]
@bsweger, @kaitlin gave me a bit more clarification on this so now I understand. While I think it is slightly confusing that you show a total of $285B (for FY14 DoD) when only a portion of that is actually obligated in the US (the only map shown), I think the issue is fixed. You can close. Thanks!

**Comment by bsweger** [comment]
Thanks @mcpeate--this has been a helpful discussion. If you have suggestions about the display of the map and surrounding data, feel free to open a new issue.
