### ISSUE TITLE
Incorrect display of R&D PSCs

### ISSUE THREAD

**Issue by mcpeate** [fedspendingtransparency/USASpending-Issue-Tracker#27]
Very minor issue: In the advanced search section, products/services that include R&D in their name display as Randd instead of displaying as "R&D". The attached screenshot displays the Product/Service "Energy Randd". 
![r dmiscoding](https://cloud.githubusercontent.com/assets/4594518/7074366/d5853bf0-dec7-11e4-85b0-1905a7f81cfa.png)

**Comment by bsweger** [comment]
@mcpeate Thanks for this report. The team confirmed that the "Energy Randd" label is a relic of the underlying product/service code list that populates this screen. We'll post any updates here as they become available.
