### ISSUE TITLE
Transactions are equated with Contracts in summary statistics for search results

### ISSUE THREAD

**Issue by mcpeate** [fedspendingtransparency/USASpending-Issue-Tracker#28]
When I perform any advanced search, the results post summary stats on number of transactions, etc. in addition to the first 10k observations. However, one such statistic allegedly reports the number of contracts. At present, either the name of this statistic or the logic calculating this statistic is incorrect. The correct label as it is currently calculated should be "contract actions". As you know, USAspending (and FPDS-NG) report contract actions. Each observation is a contract action, not a contract. The screenshot provides an example. The number of transactions (aka contract actions) matches the number of contracts-which is impossible. While I can't tell you how many contracts this search constitutes without a lot more information, I am certain that each transaction does not represent a distinct contract. I've checked this with a number of different searches, and each time, the number of transactions matches the number of contracts. Unless you create code that allows you to count the number of contracts, the summary statistic labeled 'contracts' should be renamed 'contract actions'. 
![contractactions](https://cloud.githubusercontent.com/assets/4594518/7077379/6150e2ae-dede-11e4-8d5c-a0c468287956.png)

**Comment by kaitlin** [comment]
Also reported by @Tiger74:

I ran a search the other day for DOD contracts, FY2014, and the number of transactions and the number of contracts were the same.This doesn't make sense. Take a look at the definition (pop-up box) on the USASpending.gov website for "Transactions"; it includes contracts, mods, etc. One contract can have multiple "transactions" associated with it. So 1 contract might include 12 transactions. Which means for most/all searches here, the number of transactions would be greater than the number of contracts.

I am going to update the title of this issue so it more accurately reflects the content.
