### ISSUE TITLE
total number of transactions doesn't match the sum of transaction numbers in the pie chart (agency profile page)

### ISSUE THREAD

**Issue by bsweger** [fedspendingtransparency/USASpending-Issue-Tracker#33]
Originally reported by @mcpeate in #25 

Sometimes the _Total Number of Transactions_ reported in the upper right corner of an agency profile page don't match the sum of the _Number of Transactions_ in the _Total Funds Awarded by Type_ pie chart.

Specific examples:
* [Veterans Affairs 2012](https://www.usaspending.gov/Transparency/Pages/AgencySummary.aspx?AgencyCode=3600&FiscalYear=2012). Total number of transactions = 702,933; sum of pie chart transaction numbers = 675,705
* [Dept. of Ed 2014](https://www.usaspending.gov/Transparency/Pages/AgencySummary.aspx?AgencyCode=9100&FiscalYear=2014). Total number of transaction = 662,752; sum of pie chart transaction numbers = 675,705

**Comment by USAspendingalice** [comment]
@mcpeate  We are closing this issue because the pie chart will not show negative numbers -- see the  text view of the chart.  Please feel free to come back and let us know if you have other issues. We appreciate the feedback.
