### ISSUE TITLE
why are # transactions and # contracts the same number?

### ISSUE THREAD

**Issue by Tiger74** [fedspendingtransparency/USASpending-Issue-Tracker#35]
I ran a search the other day for DOD contracts, FY2014, and  the number of transactions and the number of contracts were the same.This doesn't make sense. Take a look at the definition (pop-up box) on the USASpending.gov website for "Transactions"; it includes contracts, mods, etc. One contract can have multiple "transactions" associated with it. So 1 contract might include 12 transactions. Which means for most/all searches here, the number of transactions would be greater than the number of contracts.

**Comment by kaitlin** [comment]
Thanks for reporting @Tiger74 ! This is actually a duplicate of #28. However, that issue is not very well titled so I will update it to be more obvious and record your comments there. Thanks!

**Comment by Tiger74** [comment]
Sorry for the duplicate. Will be more diligent in the future!
