### ISSUE TITLE
advanced search: remove limit on number of fiscal years alllowed when selecting multiple spending types

### ISSUE THREAD

**Issue by bsweger** [fedspendingtransparency/USASpending-Issue-Tracker#36]
Originally reported by @michaelmcclellan in #23: 

Advance Data Search Feature – When selecting multiple “Spending Types” it limits the number of Fiscal Years one can select. Thereby, creating a burdensome for users with having to run multiple reports when needing to review multiple years (more than 3). The old USAspending.gov feature allowed for the user to select multiple years. The current state is not user friendly and is a workload burden on users. Please bring back or enable/enhancement to this feature to allow multiple FY searches regardless of how many spending types a user selects.

**Comment by askamp101** [comment]
Thank you, Becky,
We’ve added the selection of multiple FYs to the future enhancement list.
Alice

**Comment by USAspendingalice** [comment]
This has been resolved.
