### ISSUE TITLE
advanced search: add direct payment and insurance spending types

### ISSUE THREAD

**Issue by bsweger** [fedspendingtransparency/USASpending-Issue-Tracker#37]
Originally reported by @michaelmcclellan in #23: 

For “Spending Types” (on [Advanced Search screen](https://www.usaspending.gov/Pages/AdvancedSearch.aspx)) there used to be a category for Direct Payments and Insurance (now all under “Other Financial Transactions.” There does not seem to be a category for direct pay or insurance. These spending types feature should be brought back for a more simplified report for those types. Thereby, allowing a more detailed report and not have to pull “other Financial Assistance” and get data one doesn’t need. The current features are limiting and not user friendly and find the Advance Search Feature more of a burdensome issue when trying to run or retrieve data. Please bring back all those additional spending types, please.

**Comment by askamp101** [comment]
Hi Becky,
The approach to the new USAspending.gov was to use the Recovery.gov platform which only had three Award Types – contracts, grants, and loans.  At the request of OMB, we added “Other Financial Data.”
Alice

**Comment by michaelmcclellan** [comment]
Rebekah,

Just wanted to give you a heads up on the status  in reference to the spending types in DHS’s request to add the Direct Payments and Insurance.
However,  I see they do have it labeled as an enhancement in the tracker.

Thanks,

Michael O. McClellan
Program Analyst
Division of Financial Assistance Policy & Oversight (FAPO)
Office of the Chief Financial Officer (OCFO)
U.S. Department of Homeland Security (DHS)
Office: 202.447.5161
Mobile: 202.407.3513
Michael.Mcclellan@hq.dhs.gov

[cid:image001.gif@01CB9C38.C5817B50]

**Comment by bsweger** [comment]
Thanks for passing along this information @michaelmcclellan -- much appreciated. 

Apologies if the "enhancement" label caused any confusion. I added that because this ticket requested functionality that's not currently on the site (as opposed to something broken or incorrect). Sorting the issues in this way helps the team triage and prioritize.

Not every enhancement request will be incorporated into USASpending.gov. We'll post any updates here as they become available.

**Comment by gstrutt** [comment]
Alice,
Not speaking for HHS officially,but I agree that breaking out the financial assistance types to a more granular level would be helpful.  At the same time both USAS and CFDA should allow for the same types.  It doesn't do anyone any good if cfda.gov allows for cooperative agreements and USAS lumps them in as grants.  Same for direct payements and direct payments for specified use.

**Comment by USAspendingalice** [comment]
This issue has been resolved.
