### ISSUE TITLE
Duplicate bureau names on data search and advanced data search form drop-downs

### ISSUE THREAD

**Issue by bsweger** [fedspendingtransparency/USASpending-Issue-Tracker#38]
This is an offshot of an issue that @mcpeate reported when testing the fix to #31. 

The bureau drop-down list on the [data download page](https://www.usaspending.gov/DownloadCenter/Pages/DataDownload.aspx) and [Advanced Data Search](https://www.usaspending.gov/Pages/AdvancedSearch.aspx) forms has duplicate entries.

When you pick the "wrong" one, the search returns 0 records.

Some examples:
* DoD Department of Navy/Department of the Navy
* Department of Agriculture Food And Nutrition Service/Food and Nutrition Service
* Department of the Interior Indian Arts And Crafts Board/Indian Arts and Crafts Board

![screen shot 2015-04-13 at 3 59 25 pm](https://cloud.githubusercontent.com/assets/540544/7124350/20d1d736-e1f6-11e4-9a79-7c357ecf7c95.png)

**Comment by mcpeate** [comment]
@bsweger Wow. Good catch! Thanks!

**Comment by bsweger** [comment]
This appears to be an issue with the underlying data, not the user interface on USAspending.gov. While we recently updated the functionality of this website (how you access the data), the information underlying the database for USAspending.gov is dependent on data generated from agencies across government.

 Last year, Congress passed the DATA Act, and the federal government is working to establish government-wide financial data standards and increase the availability, accuracy, and usefulness of federal spending information. We have a separate forum on GitHub for providing feedback on this process and welcome your input, so that we can consider these issues as we implement the DATA Act: http://fedspendingtransparency.github.io/

**Comment by USAspendingalice** [comment]
@mcpeate We're closing this issue for now.  As the DATA Act is implemented, we expect that the data quality on USAspending.gov will improve, including the duplicate bureau names.  Please feel free to come back and let us know if you have other issues.
