### ISSUE TITLE
USAS-ITDB contract match API broken

### ISSUE THREAD

**Issue by jmendez35** [fedspendingtransparency/USASpending-Issue-Tracker#39]
The IT Dashboard Business Case API collects awarded contract data from agencies on a regular basis. These awarded contacts are checked against USASpending's API to see whether the provided data matches with FPDS/USAS. As of 3/31/2015, this API returns a 404 error.

The USASpending URL that the ITDB API calls is in the following format:
http://usaspending.gov/customcode/contractsApiXml.php?contractPIID=NRCDR0909335&contractIDVPIID=NNG07DA20B&contractAgencyID=3100&fundAgencyID=31&idvAgencyID=8000

Note: contractPIID, contractIDVPIID, contractAgencyID, fundAgencyID and idvAgencyID are parameters passed to the API based on agency submissions.

Since 3/31/2015, 250 awarded contracts across 5 agencies were updated on the IT Dashboard, all of which are marked as "No Match with USASpending" due to this issue. The ITDB will continue to mark any awarded contract updates with "No Match with USASpending" until this is resolved.

**Comment by jmendez35** [comment]
Sample XML expected from USASpending's API:

<?xml version="1.0" encoding="UTF-8"?>
<usaspendingSearchResults xmlns="http://usaspending.gov/contractsApiXml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://usaspending.gov/contractsApiXml http://usaspending.gov/schemas/contractsApiXml.xsd" xml_format_version="0.7">
    <record description="transaction list record" database="FPDS">
        <request>
            <fundingAgencyId/>
            <contractingAgencyId>7001</contractingAgencyId>
            <IDVAgencyId>7001</IDVAgencyId>
            <PIID>HSHQDC-10-A-00102</PIID>
            <IDVPIID>HSHQDC-12-J-00011</IDVPIID>
        </request>
        <response>
            <isExist>Y</isExist>
            <isPIIDMatchedFlag>N</isPIIDMatchedFlag>
            <isIDVPIIDMatchedFlag>N</isIDVPIIDMatchedFlag>
            <vendorNames>MYTHICS, INC</vendorNames>
            <contractValue>0</contractValue>
            <contractEndDate>1970-01-01</contractEndDate>
            <BaseContracts>
                <Contract>
                    <IdentifyingAgencyId>7001</IdentifyingAgencyId>
                    <TransactionNumber></TransactionNumber>
                    <effectiveDate>2011-11-10</effectiveDate>
                    <vendorName>MYTHICS, INC</vendorName>
                    <typeOfContract>Firm Fixed Price</typeOfContract>
                    <performanceBasedContract>X</performanceBasedContract>
                    <contractDescription>DEPARTMENT-WIDE ENTERPRISE LICENSE AGREEMENTS</contractDescription>
                    <solicitationId/>
                    <contractExtentCompeted>U</contractExtentCompeted>
                </Contract>
            </BaseContracts>
        </response>
    </record>
</usaspendingSearchResults>

**Comment by jmendez35** [comment]
![usaspending xml response example](https://cloud.githubusercontent.com/assets/8630426/7126759/0585488c-e20a-11e4-9624-e97f01aaf733.png)

**Comment by bsweger** [comment]
@jmendez35 Thanks for reporting this issue and providing the supporting documents/screenshots. The team is looking into it, and we'll post any updates or progress here as they become available.

**Comment by bsweger** [comment]
@jmendez35 If I understand correctly, this issue as well as #40 are related to the same private API. 

I'm going to move the additional information you posted in #40 over here to make sure the team gets the full picture in a single place. If you find any other errors related to the USAS-ITDB, feel free to post them here. Thanks again for your help!

**Comment by bsweger** [comment]
Additional error related to USAS-ITDB reported by @jmendez35: 

On the IT Dashboard, contracts that matched with USASpending (based on the API described in #39) would display a link on the public contracts page to the specific contract on USAspending's website. This page now leads to a 404 error as well.

Contracts page on ITDB:
https://my.itdashboard.gov/investment/contracts/1099

Link to contract AG3142B090033:
http://usaspending.gov/customcode/contractsItdashboard.php?contractPIID=AG3142B090033&contractIDVPIID=GS35F5014H&contractAgencyID=3142&fundAgencyID=12&idvAgencyID=1205
