### ISSUE TITLE
Product and Service List has several blanks

### ISSUE THREAD

**Issue by mcpeate** [fedspendingtransparency/USASpending-Issue-Tracker#41]
Under agency profiles/contracts data, the top "products or service" list for DOD FY14 has several different blanks sprinkled throughout the expanded list. Screenshot attached showing three such blanks. Also, what is your logic for the names of products or services? The expanded list only provides 1000, so it seems like it's not a 1:1 mapping from PSCs. Or are you just cutting off the list at the top 1000 PSCs? Is this crosswalk documentation available somewhere? 
![pscs-dodfy14](https://cloud.githubusercontent.com/assets/4594518/7142271/618a8c32-e2a5-11e4-829f-6d5f34f76aae.png)

**Comment by bsweger** [comment]
Thanks for reporting, @mcpeate. I can confirm that I see in this in other agency profiles as well. For example:

* https://www.usaspending.gov/Pages/TextView.aspx?data=AgencyProductOrService&agencycode=1200&fiscalyear=2015
* https://www.usaspending.gov/Pages/TextView.aspx?data=AgencyProductOrService&agencycode=1400&fiscalyear=2015

We'll post any updates or progress here as they become available.
