### ISSUE TITLE
PA_Agency ID missing?

### ISSUE THREAD

**Issue by Umer08** [fedspendingtransparency/USASpending-Issue-Tracker#42]
Noticed that the PA_AGENCYID in the bulk download is no longer being populated with values. Is this intentional? If so, could Spending team elaborate on the reason. 

A few sample records:

PA_REPORT_ID= 96CC38E6-F7F8-005D-F830-DCF98268CC0                        
PA_Agency ID=null      
PA_Contr_agency_ID=5700

PA_REPORT_ID= {4BE179B7-F82F-B82C-317C-B088691A7A11}                  
PA_Agency ID=null      
PA_Contr_agency_ID=2100

**Comment by bsweger** [comment]
Thanks for this report @Umer08. 

To make sure we have enough information to answer your question, can you tell us which page you were on when downloading the data (e.g., [Advanced Data Search](https://www.usaspending.gov/Pages/AdvancedSearch.aspx), [Data Download](https://www.usaspending.gov/DownloadCenter/Pages/DataDownload.aspx))?

**Comment by Umer08** [comment]
Data Download, sub-award, XML.

**Comment by bsweger** [comment]
Thank you for clarifying, @Umer08. We'll post any updates or progress here as they become available.

**Comment by bsweger** [comment]
@Umer08 A fix went in for this. I tested and was able to see prime award agency id in the download. Can you test to see if it's working for you? If so, I'll close this issue. Thanks!

**Comment by Umer08** [comment]
@bsweger the CSV looks good. I am in the process of testing the XML. I will post an update once I have verified the XML. Thank you so much for your help!
