### ISSUE TITLE
clarification requested for definition of USASpending bureaus and their relationships to award actions/spending

### ISSUE THREAD

**Issue by bsweger** [fedspendingtransparency/USASpending-Issue-Tracker#43]
This issue originates from @mcpeate and is broken out from a conversation that originally took place in #31.

>I guess the problem I'm having now is your current list of options for DOD seems to be a mixture of contracting agency, funding agency, and potentially Major Command level. So, as an example, if I search for National Guard Bureau in the USAspending data download section which searches by contracting agency (I assume), there are no records. This corroborates with FPDS-NG. If I search for them by the funding agency in FPDS-NG, they have records but no dollars. However, if I search for NGB by Major command in FPDS-NG, I see $2.1B. I guess I'm wondering where you got your list of options from. I may need a lifeline here: @romney68. If you only allow users to search by contracting agency in the bulk download section, then you should probably restrict it to the subset of contracting agencies that exist. Thoughts?

>@mcpeate If I understand correctly, you're asking for clarity on what exactly is represented in USASpending's list of bureau names and also for that list to be limited to bureaus that actually have awards records?

>@bsweger Not exactly, though it still may be a separate issue. At present, your code to identify spend/actions for a particular entity labeled "bureau" at USAspending is only pulling at the department and agency level (in FPDS-NG), yet your drop-down choices are including Major command/sub command entities. National Guard Bureau, as an example, has contract spend, but it is listed in FPDS-NG as a 'Major Command' (under the contracting agency of Army) rather than as a stand-alone agency (or 'bureau' in USAspending terminology). So it is technically incorrect for USAspending to claim that NGB (and AMC, etc.) have no contract actions/spend. As stated earlier, I'm fine if this is a separate issue.

**Comment by mcpeate** [comment]
@bsweger adding to this list of clarification/changes on DoD's "bureau" list. Not only are you listing Major commands (though your code does not search for Maj com spend), you're also listing 'bureaus' that don't enter their data into FPDS-NG (e.g., DIA).

**Comment by bsweger** [comment]
@mcpeate the team found that these questions relate to USASpending's underlying data. See the text below for more information. Thanks again for taking the time to ask these questions.
********************
This appears to be an issue with the underlying data, not the user interface on USAspending.gov. While we recently updated the functionality of this website (how you access the data), the information underlying the database for USAspending.gov is dependent on data generated from agencies across government.

Last year, Congress passed the DATA Act, and the federal government is working to establish government-wide financial data standards and increase the availability, accuracy, and usefulness of federal spending information. We have a separate forum on GitHub for providing feedback on this process and welcome your input, so that we can consider these issues as we implement the DATA Act: http://fedspendingtransparency.github.io/
