### ISSUE TITLE
Subaward summary data not displaying in IE in the Agency Profile Page

### ISSUE THREAD

**Issue by michaelmcclellan** [fedspendingtransparency/USASpending-Issue-Tracker#44]
When IE displays the summary data, it displays the full summary for a second and then omitts the subaward summary. 

In Chrome it works displays all summary data.  I have a snapshot and not sure how to attached a word or pdf file.

**Comment by bsweger** [comment]
Thanks for reporting @michaelmcclellan. To help the team troubleshoot, can you let us know:
 
* Which version of Internet Explorer you're using (I believe you can find that by clicking _Help_ and then _About Internet Explorer_)
* Which version of Windows you're using

You can't attach a PDF or Word doc here, but if you take a screenshot, you should be able to paste the resulting image into the comment box without having to put it in PDF/Word first.

**Comment by michaelmcclellan** [comment]
IE is Version 9
and
Windows 7

**Comment by bsweger** [comment]
Thanks @michaelmcclellan. Using this additional info, I haven't been able to recreate the problem you're seeing. If you're not able to post your screenshot, can you link to the page you were on and any parameters that you had selected? I want to make sure we get to the bottom of what's happening.

**Comment by michaelmcclellan** [comment]
Sorry for the delay in getting back to you. Below is the link to t he page as 

https://www.usaspending.gov/transparency/Pages/AgencySummary.aspx?AgencyCode=7000&FiscalYear=2015

Foir whatever reason it's not allowing me to post a screenshot.

**Comment by bsweger** [comment]
Thanks @michaelmcclellan. Using an IE testing site, here's what I see for IE 9. Is this what you're seeing? If not, feel free to e-mail me your image, and I'll add it here: rebecca.sweger@gsa.gov. Thanks again for the follow-up.

**IE 9**
![screen shot 2015-04-22 at 10 47 37 am](https://cloud.githubusercontent.com/assets/540544/7277745/b3c31380-e8df-11e4-82d3-0c78fdddf8fb.png)

**Chrome**
![screen shot 2015-04-22 at 11 08 10 am](https://cloud.githubusercontent.com/assets/540544/7277780/ebf302ba-e8df-11e4-976c-bb19e4596637.png)

**Comment by michaelmcclellan** [comment]
Yes for ie that is what I see and should be what you're seeing in  Chrome, correct?

Thanks!

**Comment by bsweger** [comment]
@michaelmcclellan Thanks for confirming. The team will review, and I'll post any updates here as they become available.
