### ISSUE TITLE
PrimeAward / DirectPayments and PrimeAward / Insurance

### ISSUE THREAD

**Issue by jobrieniii** [fedspendingtransparency/USASpending-Issue-Tracker#47]
Can you confirm where the resources for **Prime Award / Direct Payments** and **Prime Award / Insurance** are now (that used to be available via the Data Downloads form).

Searched around site - but didn't find any reference.  Sorry if missed...

**Comment by bsweger** [comment]
@jobrieniii Thanks for the question. You should be able to get this information by:

1. Going to the [advanced data search page](https://www.usaspending.gov/Pages/AdvancedSearch.aspx).
2. Choosing "Other Financial Assistance" as the spending type.
3. Selecting direct payments and/or insurance from the _Assistance Only_ options on the bottom right-hand corner of the page.

![screen shot 2015-04-21 at 3 00 17 pm](https://cloud.githubusercontent.com/assets/540544/7260406/c2e97e56-e837-11e4-8c67-4b1b68efb9e5.png)

I hope that helps--please let us know if you have any other questions.

**Comment by bsweger** [comment]
@jobrieniii Just circling back on this. I believe the steps above will get you the information you requested, so I'm going to close this issue out. Feel free to let us know if the issue wasn't solved, and I'll re-open it. Thanks again for the question!

**Comment by jobrieniii** [comment]
thanks @bsweger - haven't had a chance to dive in - but if I find an issue when I do I'll circle back around - thanks!
