### ISSUE TITLE
Searches take a long time

### ISSUE THREAD

**Issue by bsweger** [fedspendingtransparency/USASpending-Issue-Tracker#5]
For example, filtering on two fiscal years for loans from the Dept. of Education takes 4-5 seconds, which is too long.

**Comment by michaelmcclellan** [comment]
I am not sure if one can reopen a issue as this is still happening and it ran for 15 mins this morning and I closed the browswer and ran it again and let it sit there for another 10 mins and it was still in the generating mode.

**Comment by kaitlin** [comment]
@michaelmcclellan I've reopened the issue. Can you provide specifics on the search parameters you are using? Thanks!

**Comment by michaelmcclellan** [comment]
When searching for Prime Award data for DHS, component FEMA for Grant data for FY10. Those are my parameters and criteria, rather simple search. I do have a pdf of the page and also on the page itself it states: NOTE: While we continue to make improvements in the Download functionality, you may experience intermittent technical difficulties. We apologize for the inconvenience.
So, seems USAspend is aware of this issue. However, it’s still failing to perform its intended function.

**Comment by kaitlin** [comment]
Ah it sounds like you're talking about the [data downloads page](https://www.usaspending.gov/DownloadCenter/Pages/DataDownload.aspx), not the [advanced search page](https://www.usaspending.gov/Pages/AdvancedSearch.aspx). This ticket was originally for the advanced search taking a long time. I will close this issue again, and create a new issue for the Data Download issues.
