### ISSUE TITLE
Advanced Search - Recipient Name should search Vendor and Parent Vendor fields

### ISSUE THREAD

**Issue by betterdataneeded** [fedspendingtransparency/USASpending-Issue-Tracker#56]

**Comment by bsweger** [comment]
@betterdataneeded Thanks again for all of your suggestions. I've marked this as a request for enhancement and will post additional information/updates here as available.

**Comment by USAspendingalice** [comment]
@betterdataneeded The new keyword search has resolved this issue so we're closing.  Please feel free to come back if you have other issues.
