### ISSUE TITLE
Advanced Search - Duns search should search Vendor Duns and Parent Vendor Duns

### ISSUE THREAD

**Issue by betterdataneeded** [fedspendingtransparency/USASpending-Issue-Tracker#57]

**Comment by bsweger** [comment]
@betterdataneeded Thanks for submitting this feedback. I've marked this as a request for enhancement and will post any updates here as they become available.

**Comment by USAspendingalice** [comment]
@betterdataneeded  You can now use the keyword search to enter a vendor or parent DUNS.
