### ISSUE TITLE
Advanced Search - recipient name data field should support boolean commands

### ISSUE THREAD

**Issue by betterdataneeded** [fedspendingtransparency/USASpending-Issue-Tracker#59]

**Comment by bsweger** [comment]
@betterdataneeded Thank you very much for this feedback. I'll pass it along to the team and will update here when there is more information.

**Comment by USAspendingalice** [comment]
@betterdataneeded @michaelmcclellan The keyword search, 6-digit NAICS, and 4-digit P/S codes have been implemented on USAspending.gov.

**Comment by USAspendingalice** [comment]
@betterdataneeded  We are closing out this issue because the new keyword search support Boolean search. We appreciate your feedback and hope you'll come back if you have other issues.
