### ISSUE TITLE
Pop up Transaction Detail should default display all data fields without having to click on a dozen expansion +

### ISSUE THREAD

**Issue by betterdataneeded** [fedspendingtransparency/USASpending-Issue-Tracker#60]

**Comment by Tiger74** [comment]
You’re generating multiple emails (like the one below) with no content.

**Comment by betterdataneeded** [comment]
I do not understand your comment - the content of the issue is in the subject line

**Comment by bsweger** [comment]
@betterdataneeded Thanks for your feedback. To make sure we understand correctly, can you specify what you mean by "pop up transaction detail?" Which screen were you on when you got the pop-up?

Again, I appreciate you taking the time to weigh in, and I want to make sure we understand exactly what feature you're referring to so we can log the feedback accordingly.

**Comment by betterdataneeded** [comment]
In the Results Summary when you click on the Award ID link to get more detail
