### ISSUE TITLE
Results Summary - should display better chosen data fields

### ISSUE THREAD

**Issue by betterdataneeded** [fedspendingtransparency/USASpending-Issue-Tracker#61]
I was putting my comments in the subject line, but if you prefer I can repeat them in this box.  The results summary displayed is not the best.  I understand you probably have column limitations, but I think the old site did it better with multiple rows per record.  Data fields like PIID, Referenced PIID, Mod and description/title enabled you to more easily get a picture of what was going on.  Also helpful if there was some kind of click/sort function of displayed data fields

**Comment by bsweger** [comment]
@betterdataneeded: Thanks for taking the time to weigh in on USASpending. We'll get your feedback no matter where you put it, though the longer text box provides enough room to be very specific, if necessary.

Have you tried the [Data Download](https://www.usaspending.gov/DownloadCenter/Pages/DataDownload.aspx) screen? The information downloaded from that page does contain more detailed information like mod and PIID. If that doesn't have everything you'd like to see, feel free to update this issue with a specific list of what you think is missing.

Note that the team is still working on some problems around large downloads from this screen (see #31), but you should be able to download a smaller dataset to get an idea of the information it contains (for example: http://download.usaspending.gov/datadownlods/Contracts/ef206288/Data_Feed.csv).

**Comment by betterdataneeded** [comment]
Yes- I have seen your data download site and I am very familiar with it.  Having to go to the full data download kind of defeats the purpose of a search engine – don’t you think.

I am extraordinarily frustrated with the destruction of what was a perfectly good website and substituting it with a vastly inferior one.    I have made many comments and suggestions to improve your site & have just touched the surface– they primarily could be solved by examining the function and usability of the old website and retaining those same said functions and design.  The old website had issues, but you have really taken many steps backwards with this new one.

Even the simplest tasks are incredibly hard  on your new site – for example if I want to see full life cycle spending of a contract.  I know how to do a work around, but that is not helpful – I should be able to type in one number and get full spend history regardless of how many years back it goes.  Again I know where to go for this via the FPDS site and other repackagers, but you were making real progress with the old site in terms of not very experienced data users being able to pull data and that is no longer the case.

Peter Doran | Sr. Director Market Research | peter.doran@icfi.com<mailto:peter.doran@icfi.com> | ICF INTERNATIONAL | icfi.com<http://www.icfi.com/>
US +1 703.218.2698  UK +44 (0)203.096.4904

**Comment by mcpeate** [comment]
@bsweger I know this issue has been closed, but I want to echo the frustration and surprise I felt when I found out the new site had been stripped of most of its functionality. I've been focused on helping you fix the overtly incorrect issues on the site, but I want to revisit the diminished functionality issue once those are resolved. (The data download option is poor substitute for most of the advanced search functionality that was eliminated.)
