### ISSUE TITLE
June 16 All Contract tsv Full 2007 is invalid

### ISSUE THREAD

**Issue by JohnEFreeman** [fedspendingtransparency/USASpending-Issue-Tracker#69]
I just downloaded all Full year Archives for All Contracts as tsv files.  All went well and download was much faster than before.  I haven't checked all archives but 2007 Full is invalid in tsv.
I proceeded to download the csv Full for 2007, and it appears to be normal.  
This is a heads  up.  Can you fix the data?

Evidence:  2007_All_Contracts_Full_20150615.csv.zip is 1.20 GB and 2007_All_Contracts_Full_20150615.tsv.zip is 453 bytes.

Thanks

**Comment by USAspendingalice** [comment]
Thank you for letting us know that you were able to download the file successfully. 
Could you please clarify what you mean by "invalid" so we can investigate as we were able to download and open the tsv 2007 Full Contracts file.

**Comment by JohnEFreeman** [comment]
I would say that a file length of 453 bytes vs. the CSV file of 1.20 GB should be evidence enough.  For me to extract the CSV, I must do it manually out of my data stream, then merge it back in.  I'd much prefer to have all of the files in .tsv format.

**Comment by JohnEFreeman** [comment]
Actually, the June 16th Full Archive is not visible, but the May 16th one is. 
![june 16 usas](https://cloud.githubusercontent.com/assets/12041978/8189833/e87423da-142c-11e5-8ce3-e69de339704f.JPG)

**Comment by JohnEFreeman** [comment]
The june one is not available here, and may is 453 bytes.

**Comment by USAspendingalice** [comment]
Thank you for the clarification. The Tech Team is reviewing the May Full file now. 
We still processing the June Full files. They should be available in the next day.

**Comment by JohnEFreeman** [comment]
I only need June now.

**Comment by USAspendingalice** [comment]
@JohnEFreeman We have replicated the issue with the 2007 May file and are working on a fix.  We'll let you know when the issue has been resolved.

**Comment by USAspendingalice** [comment]
@JohnEFreeman The tsv files have been regenerated.  Please let us know if you experience further issues.  If not, then we'll close this issue in the next couple of days.

**Comment by AileenBurgman** [comment]
I will be out of the office starting  06/22/2015 and will not return until
06/29/2015.

I will not have access to email during this time, so I will respond to your
message as soon as I return.  If urgent, please contact
Randall.Forrester@fiscal.treasury.gov.  Thank you.
