### ISSUE TITLE
TSV files no longer have different separator for row and column; SSIS does not allow this.

### ISSUE THREAD

**Issue by JohnEFreeman** [fedspendingtransparency/USASpending-Issue-Tracker#70]
TSV FULL Archive files  use a TAB x09 for both column delimiter and row delimiter. This is a change from previous TSV files.  When using a TAB to separate columns, you should use a different separator for rows such as CR-LF (as was the case in the past).  This allows for control of rows even if one row is missing a TAB or has an extra TAB.  Products like SSIS, which I am using, does not allow the same separator for both columns and rows, so I am effectively dead in the water using .tsv files.

Fortunately, a sample of CSV files shows that they do maintain the distinction between column separator (',') and row separator (CR-LF).  So I will download all of the files using csv versions.  TSV in the current archive format is not useful to me anymore.  

What do other people think?  Are current tsv files of use to you?

**Comment by USAspendingalice** [comment]
Thank you for your feedback. Will discuss with Tech Team.

**Comment by USAspendingalice** [comment]
@JohnEFreeman Quick question from the Tech Team -- did this issue occur with the June TSV files? Are you able to use the May TSV files?

**Comment by JohnEFreeman** [comment]
Quick response:  I downloaded and extracted Full 2008 through Full 2015
files as of 20150515 and did not have a problem. Other years were not
available as of 20150515.  I will pull a few samples from my archive and
examine them, but if they were like June files, they would not have worked
in SSIS.  I'll respond one more time on this with definitive evidence.

 

John

**Comment by JohnEFreeman** [comment]
To clarify:

 

All of the instances of TSV format Full archives as of 20150615 (that is,
2000-2015) are formatted with a single TAB x09 at the end of each column and
at the end of each row, as far as I can tell.  Previous files that I tested
as of 20150515 and earlier had, in addition to the (") delimited variables:

 

x09  (TAB) to delimit variables or columns

x0a (LF) to end the header row (without the x0d, CR)

x0d0a (CR-LF) in combination to terminate all data rows

 

This is a very helpful combination.  For example, if a TAB is missing or an
extra TAB is embedded in a column, the CR-LF limits the problem to one row
of data.  As another example, the count of CR-LF combos is the number of
data rows.  Also important is the fact that SSIS will not allow the same
delimiter be used for columns and rows concurrently.

 

I developed a test using my hex editor and can search for alternative
delimiters without damaging the files in any way.  

 

I'll confirm what I've said after looking at 4 sample files ---- --2 from
May and 2 from April - and report one more time.

 

John 

 

 

From: John Freeman [mailto:johnefreeman@verizon.net] 
Sent: Wednesday, June 17, 2015 5:39 PM
To: 'fedspendingtransparency/USASpending-Issue-Tracker';
'fedspendingtransparency/USASpending-Issue-Tracker'
Cc: 'JohnEFreeman'
Subject: RE: [USASpending-Issue-Tracker] TSV files no longer have different
separator for row and column; SSIS does not allow this. (#70)

 

Quick response:  I downloaded and extracted Full 2008 through Full 2015
files as of 20150515 and did not have a problem. Other years were not
available as of 20150515.  I will pull a few samples from my archive and
examine them, but if they were like June files, they would not have worked
in SSIS.  I'll respond one more time on this with definitive evidence.

 

John

**Comment by JohnEFreeman** [comment]
I am reporting the results from 3 older files:  

 

Test A:  2008_All_Contracts_Full_20150515.tsv

Test B: 2006_All_Contracts_Full_20141215.tsv

Test C: 2002_All_Contracts_Full_20130715.tsv

 

I have one correction for the below email:

 

X0a (LF) can be used as a delimiter for the header row even if the header
row contains the normal row delimiter of x0d0a (CR-LF) in SSIS because SSIS
allows me to separately set the header row delimiter.  The normal row
delimiter can be CR-LF while the header row delimiter is LF.  Once the
header row is processed, the normal row delimiter will be in effect for all
of the remaining rows.  (So don't insert a header row after any data rows.)

 

The Test A file uses CR-LF as the delimiter for all rows (header or data).
This is fine.  Columns are delimited using x09(TAB).

 

The Test B and Test C files seem to use the same delimiter approach:  They
drop the x0d (CR) and use just x0a(LF), and of course x09(TAB) in tsv files.

 

Test A is the example to follow going forward.  If you get a chance to
update older tsv files that use the x0a(LF), please change row terminators
to x0d0a(CR-LF) as the May files did.   A problem can arise when someone is
extracting archive files across the full range of years:  You may be able to
process all of the files with the same delimiters set, or depending on the
tool you are using, you may have to process some files, change the
delimiter, and process the remaining files, a bit of a nuisance.

 

Delimiters do matters, especially how they interact with the tools being
used to extract them.  Done using my proposed arrangement in the previous
email plus the one correction in this email, should serve all of us well.
They are tried and haven't generated a rash of complaints.       

 

Needless to say, the same delimiter approach should be used with Full and
Delta files.

 

Perhaps I'm the only person still using tsv files.  If you haven't already,
you should take a poll to find out how many consume these archives using
tsv.  I have been forced to use csv this month, and once it's proven, I
could change to csv permanently.

 

BTW, csv files are set up with delimiters much the same as Test A.  Although
I am in the middle of my ETL cycle right now, if csv proves to work well, I
can switch to csv.  

 

You have access to the Test A file so I won't send it to you.

 

I'd like to hear what you decide to do.

 

John

 

 

 

From: John Freeman [mailto:johnefreeman@verizon.net] 
Sent: Wednesday, June 17, 2015 6:09 PM
To: 'fedspendingtransparency/USASpending-Issue-Tracker';
'fedspendingtransparency/USASpending-Issue-Tracker'
Cc: 'JohnEFreeman'
Subject: RE: [USASpending-Issue-Tracker] TSV files no longer have different
separator for row and column; SSIS does not allow this. (#70)

 

To clarify:

 

All of the instances of TSV format Full archives as of 20150615 (that is,
2000-2015) are formatted with a single TAB x09 at the end of each column and
at the end of each row, as far as I can tell.  Previous files that I tested
as of 20150515 and earlier had, in addition to the (") delimited variables:

 

x09  (TAB) to delimit variables or columns

x0a (LF) to end the header row (without the x0d, CR)

x0d0a (CR-LF) in combination to terminate all data rows

 

This is a very helpful combination.  For example, if a TAB is missing or an
extra TAB is embedded in a column, the CR-LF limits the problem to one row
of data.  As another example, the count of CR-LF combos is the number of
data rows.  Also important is the fact that SSIS will not allow the same
delimiter be used for columns and rows concurrently.

 

I developed a test using my hex editor and can search for alternative
delimiters without damaging the files in any way.  

 

I'll confirm what I've said after looking at 4 sample files ---- --2 from
May and 2 from April - and report one more time.

 

John 

 

 

From: John Freeman [mailto:johnefreeman@verizon.net] 
Sent: Wednesday, June 17, 2015 5:39 PM
To: 'fedspendingtransparency/USASpending-Issue-Tracker';
'fedspendingtransparency/USASpending-Issue-Tracker'
Cc: 'JohnEFreeman'
Subject: RE: [USASpending-Issue-Tracker] TSV files no longer have different
separator for row and column; SSIS does not allow this. (#70)

 

Quick response:  I downloaded and extracted Full 2008 through Full 2015
files as of 20150515 and did not have a problem. Other years were not
available as of 20150515.  I will pull a few samples from my archive and
examine them, but if they were like June files, they would not have worked
in SSIS.  I'll respond one more time on this with definitive evidence.

 

John

**Comment by USAspendingalice** [comment]
@JohnEFreeman We have identified the issue with the TSV files and are in the process of regenerating them.  They should be loaded on to the site within the next 2 days.

**Comment by AileenBurgman** [comment]
I will be out of the office starting  06/18/2015 and will not return until
06/19/2015.

I will respond to your email as soon as I return.  Thank you.

**Comment by USAspendingalice** [comment]
This issue has been resolved.
