### ISSUE TITLE
USASpending FY 2013 CFDA Inaccuracy for 84.027 (Special Education - Grants to States)

### ISSUE THREAD

**Issue by leveille** [fedspendingtransparency/USASpending-Issue-Tracker#73]
The reported FY 2013 total for a specific CFDA number is very, very low.

USAspending [reports about $1.6 billion in FY 2013 for CFDA number 84.027](https://www.usaspending.gov/Pages/AdvancedSearch.aspx?sub=y&ST=G&FY=2013&A=0&SS=USA&CFDA=84.027) (Special Education Grants to States).

However, the Catalog of Federal Domestic Assistance shows about $11 billion in obligations for 84.027 in FY 2013. This ~ matches the FY 2013 actual number reported by Department of Education: http://www2.ed.gov/about/overview/budget/statetables/15stbyprogram.pdf#19

Why does USAspending report a number that is only 15% of the actual total?

**Comment by USAspendingalice** [comment]
Thank you for your post and feedback. 
We display the data as it was submitted for that specific CFDA, and the data is displayed consistently across the site from the Data Download, Agency Profile, and the Advanced Data Search.
