### ISSUE TITLE
Title HTML in page is a little off

### ISSUE THREAD

**Issue by jgaviglio** [fedspendingtransparency/USASpending-Issue-Tracker#74]
https://www.usaspending.gov/Pages/TextView.aspx?data=HomeAwardTypeFunding
![image](https://cloud.githubusercontent.com/assets/11860425/8811719/cd9e8212-2fc5-11e5-9b6e-ddcd3a13b2fb.png)

**Comment by USAspendingalice** [comment]
@jgaviglio This issue will be resolved by tomorrow morning. Thank you again for bringing it to our attention.
