### ISSUE TITLE
Data Quality: Reference Data Source for Agency

### ISSUE THREAD

**Issue by HerschelC** [fedspendingtransparency/USASpending-Issue-Tracker#75]
What is the source for data in agencyid, contractingofficeagencyid, contractingofficeid, fundingrequestingagencyid, fundingrequestingofficeid, maj_agency_cat, maj_fund_agency_cat, mod_agency?

For example, 12C2: FOREST SERVICE in the snippet of 2015 contract data below (click on it to open in a larger window, sorry for the width).  

![image](https://cloud.githubusercontent.com/assets/9831612/8896615/d79b5e12-33cf-11e5-82b8-db2f379b4e2a.png)

I understand that 1200 is Department of Agriculture; C2 must mean Forest Service.  From where is this information sourced?  

This is perhaps the agency identifier from FPDS-NG - but what is the reference source?  The FPDS-NG data dictionary has no details.  The validation rules document indicates that it must be in the lookup table.  This would make sense - there should be reference data that indicates the set of valid values and the hierarchy.

However, you can also see in the screen clip that 9700 has two distinct values DEPT OF DEFENSE and Department of Defense.  This creates two separate levels of aggregation since this is two different things.  So this seems like there is more than one source since if there is one source it would likely have only one or the other at the top of the hierarchy.  

Can you provide some clarity, and ideally the reference data also available for download in csv or some format?

**Comment by USAspendingalice** [comment]
Thank you for the question. USAspending.gov does not validate the data submitted to FPDS and pulled into USAspending.gov by ATOM Feed from FPDS-NG.  So the only way to find out the source and hierarchy of the data would be from FPDS. Let us know if we can help in any other way.
