### ISSUE TITLE
Updates to USAspending.gov

### ISSUE THREAD

**Issue by USAspendingalice** [fedspendingtransparency/USASpending-Issue-Tracker#78]
Since the refresh of USAspending.gov on March 31, 2015, we have been making improvements to the site and adding some previous functionalities based on your feedback.  
For the Advanced Data Search, we've added: 
the full NAICs and Product/Service Codes
the ability to choose multiple fiscal years, spending types, and awarding/funding agencies
Sortable Search Result columns
PLUS: 
Keyword Search
the Overview of Awards by Fiscal Year trending graph
all files in the Data Archives 

Coming Up:
All fields in the Advanced Data Search download
Recipient Profiles 

We'll continue to keep you updated and look forward to your continuing feedback.

**Comment by tacuba** [comment]
Not sure if this requires a new issue to be created, but where can I find a crosswalk noting all of the Agencies and their corresponding ID number?  

For example, "7000" is linked to the "Homeland Security, Department of" (the Major Agency), and "7012" is linked to "U.S. Immigration and Customs Enforcement" (a Sub-Agency within 7000).

**Comment by USAspendingalice** [comment]
Thank you for your post.  The agency codes can be found here: http://csrc.nist.gov/publications/nistpubs/800-87-Rev1/SP800-87_Rev1-April2008Final.pdf
