### ISSUE TITLE
Duplicate Transactions Caused by Both "Active" and "Inactive" Transaction Status

### ISSUE THREAD

**Issue by banderson735** [fedspendingtransparency/USASpending-Issue-Tracker#79]
Within the data archives, specifically the all contracts full archive, I'm finding transactions that have both "Inactive" and "Active" Transaction Statuses. This is causing duplicate transactions and doubling measure values. 

The definition provided by usaspending.gov for transaction_status is "The status of the particular record, either ‘active’ or ‘inactive’.". This isn't very descriptive... are "inactive" records not relevant? Should inactive records be deleted? 

I found documentation (http://semanticommunity.info/A_USASpending.gov_Dashboard#2.2_How_to_Download_Standard_Cumulative_and_Delta_Archived_Data) stating "The transaction_status field will determine the status of the particular record as either ‘Active’ or ‘Inactive’. The transaction_status will be flagged as ‘Active’ for ‘insert/update’ records and as ‘Inactive’ for ‘delete’ records.", but this was in regards to the delta files. 

I need to know the definitions of "active"/"inactive" and how to treat these records. 

Your help is greatly appreciated and I apologize if this is documented elsewhere.

**Comment by USAspendingalice** [comment]
Thank you so much for your comment and question.

The difference between Active and Inactive is that the Inactive are deleted records.  The data from the Inactive records is not included in the totals across the site so these are duplicates. 

However, Inactive records should be included in the Delta files only so we are going to be re-running the current Full files to remove the Inactive records. We will let you know when those Full files have been uploaded to the Data Archives.

**Comment by banderson735** [comment]
Thank you for your reply. 

I think it would be helpful to have clarification of cases like this on all of the data download pages, so that downloaders now how to treat the data. 

I may be completely blind, but I have not seen any documentation (besides the link I provided above) that would have alerted me or others to this issue. 

In our case this made a huge difference as a $50 million contract was represented as $100 million.

Hopefully we were the only ones that didn't realize this was going on and it didn't ruin too many projects.
