### ISSUE TITLE
"Complete" dataset for contracts does not return any values

### ISSUE THREAD

**Issue by aglorios** [fedspendingtransparency/USASpending-Issue-Tracker#87]
The API schema listed on your data site: https://www.usaspending.gov/fpds/fpds.php?detail=c&fiscal_year=2015&stateCode=TX&max_records=10

Does not actually return any information. Please assist.

**Comment by USAspendingkevin** [comment]
The Technical Team identified an issue with the API code and has developed a fix.  The fix is being tested now and should be deployed to Production by the end of next week (June 24).
