### ISSUE TITLE
Unable to replicate state-level aggregates shown on USAspending.gov

### ISSUE THREAD

**Issue by comfymike** [fedspendingtransparency/USASpending-Issue-Tracker#88]
### SUMMARY
I want to prove that I'm interpreting this data correctly by recreating some of the values + graphs shown on this page: https://www.usaspending.gov/Transparency/Pages/StateContracts.aspx?statecode=CA&fiscalyear=2014

I've started by trying to reproduce the  **Top Prime Recipients** but, haven't been able to get things to match correctly, so I am wondering if the data being displayed on USAspending.gov is incorrect or if my procedure has flaws in it. Here are my steps:

### MY PROCEDURE

1. Started from Data Archives, selecting Fiscal Year: 2014:(https://www.usaspending.gov/DownloadCenter/Pages/dataarchives.aspx) 

2. Download both the Full and Delta files:
(2014_All_Contracts_Full_20160615.csv.zip)
(2014_All_Contracts_Delta_20160615.csv.zip)

3. Unzip and combine files

4. Filter to include only rows where [statecode = "CA: California" & transaction_status = "active"]

5. Group rows by parentdunsnumber (this seems to be the most accurate way to id the company)

After this, I'm left with the following results in the Top 5:

### MY RESULTS
**McKesson:** ............................. $4,505,424,407.80 (25,607 transactions)
**Lockheed:** .............................. $4,117,785,109.60 (1,273 transactions)
**Health Net:** ............................ $3,233,693,355 (93 transactions)
**The Boeing Company:** ............$2,113,740,595 (1,051 transactions)
**California Institute of Tech.:** ... $2,037,948,289 (2,115 transactions)

vs

### USAspending RESULTS
**McKesson:** ............................. $4,507,584,933 (25,647)
**Lockheed:** .............................. $4,460,435,528 (1,524)
**Health Net:** ............................ $3,233,693,355 (93)
**The Boeing Company:** ............ $2,113,872,488 (1,069)
**California Institute of Tech.:** ... $1,722,608,901 (1,994)
 (see full results here: https://www.usaspending.gov/Pages/TextView.aspx?data=StateMostFundedRecipientsByAwardType&AwardType=C&statecode=CA&fiscalyear=2014)

### POTENTIAL ISSUES
The Health Net numbers match, but the other company values don't.
 
Clearly, I'm missing several transactions that USAspending.gov is including, but where are they, and is there anything wrong in my procedure that explains it? Here are my guesses as to what could be wrong:

**1. New Deltas (from _next_ month's file) are included in USAspending.gov totals (before being released for download)?
2. I'm not accounting for modifications correctly? Site says they include mods in the year that the mods were made. Files don't seem to match this statement though.**
3. "CA: California" is not always used to represent California?
4. statecode is not the best field for state?
5. fiscal_year is not the best field for year?
6. Inaccurate or missing parentdunsnumber values in transactions data?
7. I'm not accounting for the 'inactive' contracts correctly
8. I should include baseandalloptionsvalue or baseandexercisedoptionsvalue in the total (though numbers still don't add up when I do)?

Lastly, I wonder if it's unrealistic to expect an exact match with the USAspending.gov results? I would expect it to be possible, but any counterarguments or reasons why not?

Thank you in advance! And despite some of the negative comments I'm seeing in here, I think the usaspending.gov site is well done, and I've been able to get quite far with the resources provided. 

Thanks again!

**Comment by AileenBurgman** [comment]
I will be out of the office starting  08/01/2016 and will not return until
08/09/2016.

I will respond to your message as soon as possible.  Thanks.
